### ISSUE TITLE
Perform validation of inputs for clarity of errors

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator#1165]
Several times I've run the Toolkit code and ended up with a NullPointerException with no indication of what's wrong.

The latest case is generating the Speech API:

```
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:246)
	at com.google.api.tools.framework.tools.ToolUtil.sanitizeSourceFiles(ToolUtil.java:169)
	at com.google.api.tools.framework.tools.ModelBuilder.parseConfigFiles(ModelBuilder.java:159)
	at com.google.api.tools.framework.tools.ModelBuilder.setup(ModelBuilder.java:48)
	at com.google.api.tools.framework.tools.ToolDriverBase.setupModel(ToolDriverBase.java:81)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:72)
	at com.google.api.codegen.CodeGeneratorTool.generate(CodeGeneratorTool.java:120)
	at com.google.api.codegen.CodeGeneratorTool.main(CodeGeneratorTool.java:92)
```

I'm assuming some filename I've passed in can't be found, or something similar - but without digging through the code, it's going to be really hard to work out what's going on. A tool user shouldn't have to look through the code to find out what they're doing wrong, if they're passing in invalid input.

**Comment by techpavan** [comment]
Just to help others who might end up here, I encountered the same issue and the cause was due the files being inaccessible. In my case, it was a git bash environment on Windows platform and the file path passed on was in Windows format (\), changing it to Linux format(/) helped.

**Comment by iantalarico** [comment]
I'm hitting the same issue, have anyone had luck figuring this out?

**Comment by eoogbe** [comment]
@jskeet Can you add a priority to this?

**Comment by jskeet** [comment]
Set as P2, but fairly arbitrarily. It will always be "nice to have" but there are *lots* of these. Probably a good candidate for a fixit at some point.

**Comment by eoogbe** [comment]
Another case of this issue occurs with [GapicInterfaceConfig](https://github.com/googleapis/gapic-generator/blob/169f401c59e2b5967d0e4ea581b71d075f50a7e7/src/main/java/com/google/api/codegen/config/GapicInterfaceConfig.java#L125). We null out the `methodConfigMap` on error, but don't check the error before using the null value, causing an NPE far from the source.

Also this error message could use some clarifying:
> request_object_method incompatible with streaming method

It's not obvious what `request_object_method` is, why it's incompatible with streaming, and how to fix it.

Gonna look into improving the design, so its not so null-happy, and making clearer error messages.

**Comment by eoogbe** [comment]
Will be replaced by proto-based config format
