### ISSUE TITLE
Generated code produces unit tests that don't pass

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator#2089]
Trying to generate the AutoML client library.  After generating the code, I am running `npm test` and getting this now:

```
  PredictionServiceClient
    predict
      ✓ invokes predict without error (291ms)
      ✓ invokes predict with error

  AutoMlClient
    createDataset
      1) invokes createDataset without error
      2) invokes createDataset with error
    getDataset
      3) invokes getDataset without error
      4) invokes getDataset with error
    listDatasets
      5) invokes listDatasets without error
      6) invokes listDatasets with error
    deleteDataset
      7) invokes deleteDataset without error
      8) invokes deleteDataset with error
      9) has longrunning decoder functions
    importData
      10) invokes importData without error
      11) invokes importData with error
      12) has longrunning decoder functions
    exportData
      13) invokes exportData without error
      14) invokes exportData with error
      15) has longrunning decoder functions
    createModel
      16) invokes createModel without error
      17) invokes createModel with error
      18) has longrunning decoder functions
    getModel
      19) invokes getModel without error
      20) invokes getModel with error
    listModels
      21) invokes listModels without error
      22) invokes listModels with error
    deleteModel
      23) invokes deleteModel without error
      24) invokes deleteModel with error
      25) has longrunning decoder functions
    deployModel
      26) invokes deployModel without error
      27) invokes deployModel with error
    undeployModel
      28) invokes undeployModel without error
      29) invokes undeployModel with error
    getModelEvaluation
      30) invokes getModelEvaluation without error
      31) invokes getModelEvaluation with error
    listModelEvaluations
      32) invokes listModelEvaluations without error
      33) invokes listModelEvaluations with error


  2 passing (2s)
  33 failing

  1) AutoMlClient
       createDataset
         invokes createDataset without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:91:20)

  2) AutoMlClient
       createDataset
         invokes createDataset with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:128:20)

  3) AutoMlClient
       getDataset
         invokes getDataset without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:159:20)

  4) AutoMlClient
       getDataset
         invokes getDataset with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:194:20)

  5) AutoMlClient
       listDatasets
         invokes listDatasets without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:223:20)

  6) AutoMlClient
       listDatasets
         invokes listDatasets with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:257:20)

  7) AutoMlClient
       deleteDataset
         invokes deleteDataset without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:286:20)

  8) AutoMlClient
       deleteDataset
         invokes deleteDataset with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:315:20)

  9) AutoMlClient
       deleteDataset
         has longrunning decoder functions:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.it (test/gapic-v1beta1.js:342:20)

  10) AutoMlClient
       importData
         invokes importData without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:353:20)

  11) AutoMlClient
       importData
         invokes importData with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:384:20)

  12) AutoMlClient
       importData
         has longrunning decoder functions:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.it (test/gapic-v1beta1.js:413:20)

  13) AutoMlClient
       exportData
         invokes exportData without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:424:20)

  14) AutoMlClient
       exportData
         invokes exportData with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:455:20)

  15) AutoMlClient
       exportData
         has longrunning decoder functions:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.it (test/gapic-v1beta1.js:484:20)

  16) AutoMlClient
       createModel
         invokes createModel without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:495:20)

  17) AutoMlClient
       createModel
         invokes createModel with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:533:20)

  18) AutoMlClient
       createModel
         has longrunning decoder functions:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.it (test/gapic-v1beta1.js:562:20)

  19) AutoMlClient
       getModel
         invokes getModel without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:573:20)

  20) AutoMlClient
       getModel
         invokes getModel with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:608:20)

  21) AutoMlClient
       listModels
         invokes listModels without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:637:20)

  22) AutoMlClient
       listModels
         invokes listModels with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:671:20)

  23) AutoMlClient
       deleteModel
         invokes deleteModel without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:700:20)

  24) AutoMlClient
       deleteModel
         invokes deleteModel with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:729:20)

  25) AutoMlClient
       deleteModel
         has longrunning decoder functions:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.it (test/gapic-v1beta1.js:756:20)

  26) AutoMlClient
       deployModel
         invokes deployModel without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:767:20)

  27) AutoMlClient
       deployModel
         invokes deployModel with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:800:20)

  28) AutoMlClient
       undeployModel
         invokes undeployModel without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:829:20)

  29) AutoMlClient
       undeployModel
         invokes undeployModel with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:862:20)

  30) AutoMlClient
       getModelEvaluation
         invokes getModelEvaluation without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:891:20)

  31) AutoMlClient
       getModelEvaluation
         invokes getModelEvaluation with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:926:20)

  32) AutoMlClient
       listModelEvaluations
         invokes listModelEvaluations without error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:955:20)

  33) AutoMlClient
       listModelEvaluations
         invokes listModelEvaluations with error:
     TypeError: Cannot read property 'decode' of null
      at new AutoMlClient (src/v1beta1/auto_ml_client.js:196:31)
      at Context.done (test/gapic-v1beta1.js:989:20)



npm ERR! code ELIFECYCLE
npm ERR! errno 33
npm ERR! @google-cloud/automl@0.1.0 cover: `nyc --reporter=lcov mocha --require intelli-espower-loader test/*.js && nyc report`
npm ERR! Exit status 33
npm ERR! 
npm ERR! Failed at the @google-cloud/automl@0.1.0 cover script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beckwith/.npm/_logs/2018-06-19T16_22_23_217Z-debug.log
run: Oh no! Test failed after 7.25s.
npm ERR! Test failed.  See above for more details.
beckwith-macbookpro2:nodejs-automl beckwith$ 
```

If I had to guess, it looks like an issue with nodejs-proto-files.

**Comment by JustinBeckwith** [comment]
FYI @ethanbao

**Comment by alexander-fenster** [comment]
I've never seen this one so I assume it's something to do with AutoML GAPIC yaml, service yaml, or protos. I will investigate.

**Comment by alexander-fenster** [comment]
Fixed this issue in the (internal) proto file. The file defining long running operations metadata was not included from the main service proto file which caused Node.js generated code to fail.
