### ISSUE TITLE
Container Analysis v1beta1 fails to generate

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2454]
```
[35martman> [34mjava -cp /tmp/workspace/gapic-generator/build/libs/gapic-generator-latest-fatjar.jar com.google.api.codegen.GeneratorMain LEGACY_GAPIC_AND_PACKAGE --descriptor_set=/tmp/artman-genfiles/google-cloud-containeranalysis-v1beta1.desc --package_yaml2=/tmp/artman-genfiles/java_google-cloud-containeranalysis-v1beta1_package2.yaml --output=/tmp/artman-genfiles/java/gapic-google-cloud-containeranalysis-v1beta1 --language=java --service_yaml=/tmp/workspace/googleapis/google/devtools/containeranalysis/containeranalysis_v1beta1.yaml --gapic_yaml=/tmp/workspace/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis_gapic.yaml[0m
[31martman.output >
[37m[33mWARNING: [0mtoplevel: (lint) control-presence: Service containeranalysis.googleapis.com does not have control environment configured.

[31mERROR: [0mtoplevel: Unexpected exception:
java.lang.NullPointerException
	at com.google.api.codegen.transformer.GapicInterfaceContext.createGrpcRerouteMap(GapicInterfaceContext.java:87)
	at com.google.api.codegen.transformer.GapicInterfaceContext.create(GapicInterfaceContext.java:76)
	at com.google.api.codegen.transformer.java.JavaGapicSurfaceTransformer.createInterfaceContext(JavaGapicSurfaceTransformer.java:89)
	at com.google.api.codegen.transformer.java.JavaGapicSurfaceTransformer.createInterfaceContext(JavaGapicSurfaceTransformer.java:36)
	at com.google.api.codegen.transformer.java.JavaSurfaceTransformer.transform(JavaSurfaceTransformer.java:123)
	at com.google.api.codegen.transformer.java.JavaGapicSurfaceTransformer.transform(JavaGapicSurfaceTransformer.java:74)
	at com.google.api.codegen.transformer.java.JavaGapicSurfaceTransformer.transform(JavaGapicSurfaceTransformer.java:36)
	at com.google.api.codegen.gapic.GapicGenerator.generate(GapicGenerator.java:64)
	at com.google.api.codegen.gapic.GapicGeneratorApp.process(GapicGeneratorApp.java:174)
	at com.google.api.tools.framework.tools.GenericToolDriverBase.run(GenericToolDriverBase.java:90)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:73)
	at com.google.api.codegen.GeneratorMain.gapicGeneratorMain(GeneratorMain.java:305)
	at com.google.api.codegen.GeneratorMain.main(GeneratorMain.java:173)
```

**Comment by andreamlin** [comment]
See https://circleci.com/gh/googleapis/gapic-generator/10384#artifacts/containers/0 and its log file for the artman failure when generating any container analysis v1beta1 client.

**Comment by andreamlin** [comment]
This is locally reproducible, and it was a regression introduced by the latest commit 1add5a8ba75e29a80613fb2a187a46c08887434a
