### ISSUE TITLE
Sample cannot print results from LRO, field not found on Operation

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2457]
When generating a sample for a LRO method, I get:

```
java.lang.NullPointerException: LongRunningRecognize:speech_transcribe_async_gcs: type ProtoTypeRef{protoType=google.longrunning.Operation} does not have field results
```

To reproduce, here's a diff you can add to the V1 Speech GAPIC config
`google/cloud/speech/v1/cloud_speech_gapic.yaml`

```diff
+    samples:
+      standalone:
+      - region_tag: speech_transcribe_async_gcs
+        value_sets: ["speech_transcribe_async_gcs"]
+        calling_forms: ".*"
+    sample_value_sets:
+    - id: speech_transcribe_async_gcs
+      on_success:
+      - print:
+          - "Print out a field on the response: %s"
+          - $resp.results[0].alternatives[0].transcript
```

`$resp` isn't getting set to the response message type ☹️

/cc @pongad 
/fyi @vchudnov-g @hzyi-google

**Comment by beccasaurus** [comment]
I'm trying to generate Python, fwiw, not Java

**Comment by beccasaurus** [comment]
```
+ docker run --rm --volume /Users/rebeccataylor/code/googleapis:/googleapis --volume /Users/rebeccataylor/code/gapic-generator:/toolkit --volume /Users/rebeccataylor/code/python-docs-samples/speech/generated-samples/output:/googleapis/artman-genfiles --workdir /googleapis --env RUNNING_IN_ARTMAN_DOCKER=True googleapis/artman /bin/bash -c 
'artman --local --config /googleapis/google/cloud/speech/artman_speech_v1.yaml 
generate python_gapic'

artman> Final args:
artman>   api_name: speech
artman>   api_version: v1
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: /googleapis/artman-genfiles/python/speech-v1
artman>   gapic_yaml: /googleapis/google/cloud/speech/v1/cloud_speech_gapic.yaml
artman>   generator_args: null
artman>   import_proto_path:
artman>     - /googleapis
artman>   language: python
artman>   organization_name: google-cloud
artman>   output_dir: /googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: google-common-protos
artman>   root_dir: /googleapis
artman>   service_yaml: /googleapis/google/cloud/speech/speech_v1.yaml
artman>   src_proto_path:
artman>     - /googleapis/google/cloud/speech/v1
artman>   toolkit_path: /toolkit
artman>   
artman> Creating GapicClientPipeline.
artman.output >
WARNING: toplevel: (lint) control-presence: Service speech.googleapis.com does not have control environment configured.
ERROR: toplevel: Unexpected exception:
java.lang.NullPointerException: LongRunningRecognize:speech_transcribe_async_gcs: type ProtoTypeRef{protoType=google.longrunning.Operation} does not have field results
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1268)
	at com.google.api.codegen.transformer.OutputTransformer.accessorNewVariable(OutputTransformer.java:341)
	at com.google.api.codegen.transformer.OutputTransformer.loopView(OutputTransformer.java:179)
	at com.google.api.codegen.transformer.OutputTransformer.toView(OutputTransformer.java:129)
	at com.google.api.codegen.transformer.OutputTransformer.lambda$toViews$0(OutputTransformer.java:105)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.google.api.codegen.transformer.OutputTransformer.toViews(OutputTransformer.java:106)
	at com.google.api.codegen.transformer.SampleTransformer.generateSamples(SampleTransformer.java:258)
	at com.google.api.codegen.transformer.SampleTransformer.generateSamples(SampleTransformer.java:147)
	at com.google.api.codegen.transformer.DynamicLangApiMethodTransformer.generateMethodCommon(DynamicLangApiMethodTransformer.java:233)
	at com.google.api.codegen.transformer.DynamicLangApiMethodTransformer.generateLongRunningMethod(DynamicLangApiMethodTransformer.java:112)
	at com.google.api.codegen.transformer.py.PythonMethodViewGenerator.generateOneApiMethod(PythonMethodViewGenerator.java:70)
	at com.google.api.codegen.transformer.py.PythonMethodViewGenerator.lambda$generateApiMethods$0(PythonMethodViewGenerator.java:52)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.google.api.codegen.transformer.py.PythonMethodViewGenerator.generateApiMethods(PythonMethodViewGenerator.java:53)
	at com.google.api.codegen.transformer.py.PythonGapicSamplesTransformer.generateSampleClasses(PythonGapicSamplesTransformer.java:149)
	at com.google.api.codegen.transformer.py.PythonGapicSamplesTransformer.generateSampleFiles(PythonGapicSamplesTransformer.java:106)
	at com.google.api.codegen.transformer.py.PythonGapicSamplesTransformer.transform(PythonGapicSamplesTransformer.java:87)
	at com.google.api.codegen.transformer.py.PythonGapicSamplesTransformer.transform(PythonGapicSamplesTransformer.java:53)
	at com.google.api.codegen.gapic.GapicGenerator.generate(GapicGenerator.java:64)
	at com.google.api.codegen.gapic.GapicGeneratorApp.process(GapicGeneratorApp.java:174)
	at com.google.api.tools.framework.tools.GenericToolDriverBase.run(GenericToolDriverBase.java:90)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:73)
	at com.google.api.codegen.GeneratorMain.gapicGeneratorMain(GeneratorMain.java:305)
	at com.google.api.codegen.GeneratorMain.main(GeneratorMain.java:173)
```

**Comment by vchudnov-g** [comment]
Ah, sorry, we assumed incorrectly. We'll look into this.
