### ISSUE TITLE
php generation for BigQuery v2 fails

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2691]
See https://circleci.com/gh/googleapis/googleapis/1623?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

stack trace:
```
java.lang.IllegalStateException: A HttpRule option must be defined.
	at com.google.api.codegen.transformer.php.PhpGapicSurfaceTransformer.getHttpRule(PhpGapicSurfaceTransformer.java:493)
	at com.google.api.codegen.transformer.php.PhpGapicSurfaceTransformer.generateRestInterfaceConfigViews(PhpGapicSurfaceTransformer.java:325)
	at com.google.api.codegen.transformer.php.PhpGapicSurfaceTransformer.buildRestConfigViewModel(PhpGapicSurfaceTransformer.java:298)
	at com.google.api.codegen.transformer.php.PhpGapicSurfaceTransformer.transform(PhpGapicSurfaceTransformer.java:152)
	at com.google.api.codegen.transformer.php.PhpGapicSurfaceTransformer.transform(PhpGapicSurfaceTransformer.java:139)
	at com.google.api.codegen.transformer.php.PhpGapicSurfaceTransformer.transform(PhpGapicSurfaceTransformer.java:75)
	at com.google.api.codegen.gapic.GapicGenerator.generate(GapicGenerator.java:64)
	at com.google.api.codegen.gapic.GapicGeneratorApp.process(GapicGeneratorApp.java:179)
	at com.google.api.tools.framework.tools.GenericToolDriverBase.run(GenericToolDriverBase.java:90)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:73)
	at com.google.api.codegen.GeneratorMain.gapicGeneratorMain(GeneratorMain.java:309)
	at com.google.api.codegen.GeneratorMain.main(GeneratorMain.java:175)
```

This API was just introduced to googleapis

**Comment by andreamlin** [comment]
note: we should revert https://github.com/googleapis/artman/pull/599 and remove this api from the artman smoke test whitelist once this is fixed.

**Comment by hzyi-google** [comment]
This issue doesn't seem fixable from the generator - PHP uses protobuf over HTTP transport model. If there are methods without HTTP annotation then there's no way to generate a PHP gapic.
