### ISSUE TITLE
SampleGen: my java sample works for previous version, but doesn't work in current version

### ISSUE THREAD

**Issue by munkhuushmgl** [googleapis/gapic-generator#2818]
`artman.output >
WARNING: toplevel: (lint) control-presence: Service automl.googleapis.com does not have control environment configured.
WARNING: /Users/munkhbayarg/apis/googleapis/google/cloud/automl/automl_v1beta1.yaml:108: http rule has selector(s) 'google.iam.v1.IAMPolicy.SetIamPolicy' that do not match and are not shadowed by other rules.
WARNING: /Users/munkhbayarg/apis/googleapis/google/cloud/automl/automl_v1beta1.yaml:115: http rule has selector(s) 'google.iam.v1.IAMPolicy.GetIamPolicy' that do not match and are not shadowed by other rules.
WARNING: /Users/munkhbayarg/apis/googleapis/google/cloud/automl/automl_v1beta1.yaml:120: http rule has selector(s) 'google.iam.v1.IAMPolicy.TestIamPermissions' that do not match and are not shadowed by other rules.
ERROR: toplevel: Unexpected exception:
java.lang.NullPointerException
	at com.google.api.codegen.transformer.InitCodeTransformer.getCliFlagDefaultValue(InitCodeTransformer.java:941)
	at com.google.api.codegen.transformer.InitCodeTransformer.buildInitCodeView(InitCodeTransformer.java:443)
	at com.google.api.codegen.transformer.InitCodeTransformer.buildInitCodeViewRequestObject(InitCodeTransformer.java:293)
	at com.google.api.codegen.transformer.InitCodeTransformer.generateInitCode(InitCodeTransformer.java:129)
	at com.google.api.codegen.transformer.SampleTransformer.generateSample(SampleTransformer.java:229)
	at com.google.api.codegen.transformer.SampleTransformer.generateSamples(SampleTransformer.java:220)
	at com.google.api.codegen.transformer.SampleTransformer.generateSamples(SampleTransformer.java:167)
	at com.google.api.codegen.transformer.SampleTransformer.generateSamples(SampleTransformer.java:133)
	at com.google.api.codegen.transformer.StaticLangApiMethodTransformer.setRequestObjectMethodFields(StaticLangApiMethodTransformer.java:791)
	at com.google.api.codegen.transformer.StaticLangApiMethodTransformer.generateRequestObjectMethod(StaticLangApiMethodTransformer.java:344)
	at com.google.api.codegen.transformer.StaticLangApiMethodTransformer.generateRequestObjectMethod(StaticLangApiMethodTransformer.java:329)
	at com.google.api.codegen.transformer.java.JavaMethodViewGenerator.generateApiMethods(JavaMethodViewGenerator.java:183)
	at com.google.api.codegen.transformer.java.JavaGapicSamplesTransformer.generateSampleFiles(JavaGapicSamplesTransformer.java:96)
	at com.google.api.codegen.transformer.java.JavaGapicSamplesTransformer.transform(JavaGapicSamplesTransformer.java:77)
	at com.google.api.codegen.transformer.java.JavaGapicSamplesTransformer.transform(JavaGapicSamplesTransformer.java:48)
	at com.google.api.codegen.gapic.GapicGenerator.generate(GapicGenerator.java:64)
	at com.google.api.codegen.gapic.GapicGeneratorApp.process(GapicGeneratorApp.java:181)
	at com.google.api.tools.framework.tools.GenericToolDriverBase.run(GenericToolDriverBase.java:90)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:73)
	at com.google.api.codegen.GeneratorMain.gapicGeneratorMain(GeneratorMain.java:309)
	at _com.google.api.codegen.GeneratorMain.main(GeneratorMain.java:175)`_

**Comment by munkhuushmgl** [comment]
Never mind, it was missing default value for some parameter.
