### ISSUE TITLE
Samplegen: Streaming in Python Speech-to-Text

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2977]
@googleapis/samplegen 

[speech_streaming.yaml](https://paste.googleplex.com/5401745645633536)

[speech_streaming.py](https://paste.googleplex.com/4637460141178880)

[handwritten_speech_streaming.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming.py)

Error:
```
Traceback (most recent call last):
  File "samples/v1/speech_streaming_recognize.py", line 80, in <module>
    main()
  File "samples/v1/speech_streaming_recognize.py", line 77, in main
    sample_streaming_recognize(args.path)
  File "samples/v1/speech_streaming_recognize.py", line 48, in sample_streaming_recognize
    for response_item in client.streaming_recognize(requests):
TypeError: streaming_recognize() missing 1 required positional argument: 'requests'
```

Cause:
Generated: `client.streaming_recognize(requests)`
Handwritten: `client.streaming_recognize(streaming_config, requests)`

Reason: Handwritten Layers.
https://github.com/googleapis/google-cloud-python/blob/master/speech/google/cloud/speech_v1/helpers.py

**Comment by nnegrey** [comment]
If you make the quick change by hand: 
```
request = {'audio_content': audio_content}
requests = [request]
for response_item in client.streaming_recognize(streaming_config, requests):
```

You still get some other error:
```
Traceback (most recent call last):
  File "samples/v1/speech_streaming_recognize.py", line 80, in <module>
    main()
  File "samples/v1/speech_streaming_recognize.py", line 77, in main
    sample_streaming_recognize(args.path)
  File "samples/v1/speech_streaming_recognize.py", line 48, in sample_streaming_recognize
    for response_item in client.streaming_recognize(streaming_config, requests):
  File "/Users/nnegrey/homebrew/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Exception serializing request!
```

**Comment by nnegrey** [comment]
To get it working, had to modify these lines to use the protobuf objects.

OLD:
```
  config = speech_v1.'encoding': encoding, 'sample_rate_hertz': sample_rate_hertz, 'language_code': language_code}
  streaming_config = {'config': config}
  with io.open(path, 'rb') as f:
    audio_content = f.read()
  request = {'audio_content': audio_content}
```
NEW:
```
  config = speech_v1.types.RecognitionConfig(encoding=encoding, sample_rate_hertz=sample_rate_hertz, language_code=language_code)
  streaming_config = speech_v1.types.StreamingRecognitionConfig(config=config)
  with io.open(path, 'rb') as f:
    audio_content = f.read()
  request = speech_v1.types.StreamingRecognizeRequest(audio_content=audio_content)
```

**Comment by nnegrey** [comment]
Might even be because the helper method expects objects of protbuf type.

**Comment by software-dov** [comment]
I was confused at first because I couldn't see how the handwritten helper was getting enmeshed in the construction of the client.

It looks like the primary reason for the handwritten layer is the dual-state config/request; is that a common pattern for streaming methods? Do we need to augment the client library surface to better handle streaming methods? I'm hesitant to start discussing fixing this particular issue without talking about the more general defects first.

**Comment by hzyi-google** [comment]
blocked by: https://github.com/protocolbuffers/protobuf/issues/6746

**Comment by vchudnov-g** [comment]
Any updates, @software-dov ?
